# Generated by Django 6.0.4 on 2026-05-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('Mathématique', 'Mathématique'), ('Physique', 'Physique'), ('Littérature', 'Littérature'), ('Droit', 'Droit'), ("Memoire de fin d'étude", "Memoire de fin d'étude"), ('Thèse', 'Thèse'), ('Biologie', 'Biologie'), ('Science de la Vie et de la Terre', 'Science de la Vie et de la Terre'), ('Mécanique', 'Mécanique'), ('Science agronomique', 'Science agronomique'), ('Mécanique', 'Mécanique'), ('Production Animale', 'Production Animale')], max_length=150),
        ),
    ]
